name: Deploy New App Version (Backend)

on:
  push:
    branches:
      - main
    paths:
      - 'FrontEnd/**' # Adjust this path as needed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Package artifact
        run: zip -r spinterestfront.zip *


      - name: Upload artifact to S3
        run: aws s3 cp spinterestfront.zip s3://${{ secrets.BUCKET_NAME }}/spinterestfront-${{ github.run_id }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: spinterest-build-${{ github.run_id }}
          aws-region: eu-west-1
          
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: npm install
        
      - name: Genrate Deployment Package
        run: zip -r nodejs-app-build.zip *
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          application_name: ${{ secrets.FRONTEND_APP_NAME }}
          environment_name: ${{ secrets.FRONTEND_ENV_NAME }}
          version_label: ${{ github.run_id }}
          region: eu-west-1
          deployment_package: nodejs-app-build.zip
